### PR TITLE
resolves #135, zero-length args input to cast_args

### LINKED ISSUE #135: cast_args cant handle zero length args
@Roger-luo 

When upgrading to 0.11 from 0.10.2, I had a precompilation error which appears to be due to the fact that `cast_args` method doesn't seem to be able to handle a zero-length `args` input gracefully. I have a couple commands that I've casted that have zero arguments and so it didn't like these at all.

Snapshot of stacktrace:
```
ERROR: LoadError: BoundsError: attempt to access 0-element Vector{ComoniconTypes.Argument} at index [0]
Stacktrace:
  [1] getindex
    @ .\array.jl:801 [inlined]
  [2] last
    @ .\abstractarray.jl:437 [inlined]
  [3] cast_args
    @ ~\.julia\packages\Comonicon\qwttE\src\cast.jl:297 [inlined]
  [4] cast(f::Function, name::String, args::Vector{Comonicon.JLArgument}, options::Vector{Comonicon.JLOption}, flags::Vector{Comonicon.JLFlag}, line::LineNumberNode)
    @ Comonicon ~\.julia\packages\Comonicon\qwttE\src\cast.jl:278
```

I've got a PR that fixes this on my end that I will submit for your approval.

### PR DESCRIPTION
**Pull request by SamRodkey**
Hopefully this works for you, it seems like it just needs to return an empty vector of expected type and a nothing. Testing this local resolved the issue for me?

### CODE REVIEW

**Comment by Roger-luo** [comment]
thanks! can we also have your case as a test here? this would prevent future updates of breaking things

**Comment by SamRodkey** [comment]
Hmmm my test case is a CLI package... let me see if there is a way to distill it down into something testable.

**Comment by SamRodkey** [comment]
@Roger-luo Added a zero argument casted command to FakePkg, hopefully that met the intent for testing.

**Comment by Roger-luo** [comment]
just waiting for CI, and this would be good to merge
